channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - psutil==7.0.0
  - scikit-learn==1.5.0
  - scipy==1.13.1
name: mlflow-env
