channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.3.2
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==19.0.1
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
